language: node_js
node_js:
  - 10
  - 8
  - 6
cache: yarn
before_install: yarn add -D coveralls
jobs:
  include:
    - stage: Coverage
      node_js: node
      script: yarn jest --coverage --coverageReporters=text-lcov | yarn coveralls
